AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless application with consumer (SQS subscriber) Lambda function

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
  FunctionName:
    Type: String
    Description: Name of the consumer Lambda function
  LambdaExecutionRoleArn:
    Type: String
    Description: ARN of the existing IAM role for the consumer Lambda execution
  QueueArn:
    Type: String
    Description: ARN of the existing SQS queue

Outputs:
  FunctionArn:
    Description: ARN of the consumer Lambda function
    Value: !GetAtt Function.Arn

  FunctionName:
    Description: Name of the consumer Lambda function
    Value: !Ref Function

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      Runtime: python3.14
      Handler: app.consumer.lambda_handler
      CodeUri: lambda.zip
      Role: !Ref LambdaExecutionRoleArn
      Timeout: 300
      MemorySize: 128
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref QueueArn
            BatchSize: 1
            Enabled: true
            FunctionResponseTypes:
              - ReportBatchItemFailures
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: !Ref FunctionName
          POWERTOOLS_LOG_LEVEL: INFO
      Tags:
        Project: !Ref ProjectName

