AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless application with consumer (SQS subscriber) Lambda function

Parameters:
  AppTagKey:
    Type: String
    Description: Tag key for the application
  AppTagValue:
    Type: String
    Description: Tag value for the application
  FunctionName:
    Type: String
    Description: Name of the consumer Lambda function
  ConsumerExecutionRoleArn:
    Type: String
    Description: ARN of the existing IAM role for the consumer Lambda execution
  QueueArn:
    Type: String
    Description: ARN of the existing SQS queue

Outputs:
  ConsumerFunctionArn:
    Description: ARN of the consumer Lambda function
    Value: !GetAtt ConsumerFunction.Arn

  ConsumerFunctionName:
    Description: Name of the consumer Lambda function
    Value: !Ref ConsumerFunction

Resources:
  ConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      Runtime: python3.14
      Handler: app.consumer.lambda_handler
      CodeUri: lambda.zip
      Role: !Ref ConsumerExecutionRoleArn
      Timeout: 300
      MemorySize: 128
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref QueueArn
            BatchSize: 10
            Enabled: true
            FunctionResponseTypes:
              - ReportBatchItemFailures
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: !Ref FunctionName
          POWERTOOLS_LOG_LEVEL: INFO
      Tags:
          - Key: !Ref AppTagKey
            Value: !Ref AppTagValue

