---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for SQS queue policy

Parameters:
  QueueArn:
    Type: String
    Description: ARN of the SQS queue
  QueueUrl:
    Type: String
    Description: URL of the SQS queue
  ProducerRoleArn:
    Type: String
    Description: ARN of the producer IAM role
  ConsumerRoleArn:
    Type: String
    Description: ARN of the consumer IAM role

Resources:
  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref QueueUrl
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref ProducerRoleArn
            Action: "SQS:SendMessage"
            Resource: !Ref QueueArn
          - Effect: Allow
            Principal:
              AWS: !Ref ConsumerRoleArn
            Action:
              - "SQS:ReceiveMessage"
              - "SQS:DeleteMessage"
              - "SQS:GetQueueAttributes"
            Resource: !Ref QueueArn
