name: Main
run-name: Build & deploy 🚀
on: [push]

jobs:
  deploy-aws-app:
    name: Deploy AWS Application
    uses: mb-dot-dev/reusable-workflows/.github/workflows/deploy-cloudformation.yaml@main
    with:
      stack-name: stockholm-application
      template: aws/application.yml
      project: stockholm
